multimedia/urls.py
from django.conf.urls.defaults import *

from multimedia.models import Slideshow
from multimedia.views import detail, slideshow_list

info_dict = {
   'queryset': Slideshow.objects.all().order_by('-date'),
}

urlpatterns = patterns('',
    url(r'^$', slideshow_list, name="slideshow-list"),
    url(r'^(?P<multimedia_id>\d+)/$', detail, name="slideshow-detail"),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps import Sitemap, FlatPageSitemap, GenericSitemap
from django.contrib import admin

from blog.models import *
from blog.views import artists, artist_posts, LatestPost
from music.models import *
from gig.views import GigsFeed

from settings import MEDIA_ROOT

admin.autodiscover()


class BaseSitemap(Sitemap):
    priority = 0.8

    def items(self):
        return ['/', '/blog/', '/gig/', '/link/', '/album/']

    def location(self, obj):
        return obj

feeds = {
    'latest': LatestPost,
    'concerts': GigsFeed,
}

blog_sitemap_dict = {
    'queryset': Post.objects.all(),
    'date_field': 'date',
}

sitemaps = {
    'flatpages': FlatPageSitemap,
    'blog': GenericSitemap(blog_sitemap_dict),
    'list': BaseSitemap(),
    'album': AlbumSitemap(),
    'song': SongSitemap(),
}

urlpatterns = patterns('',
    url(r'^contact/', include('contact_form.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^map/', artists, name="map"),
    url(r'^ref/(?P<object_id>\d+)/$', artist_posts, name="artist-posts"),
    url(r'^gig/', include('gig.urls')),
    url(r'^link/$', include('link.urls')),
    url(r'^music/', include('music.urls')),
    url(r'^multimedia/', include('multimedia.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^feeds/latest/$', LatestPost()),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps})
)

urlpatterns += patterns('django.views.generic.simple',
    ('^$', 'redirect_to', {'url': 'blog/'}),
)

try:
    import settings_local
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, 'show_indexes': True}),
    )
    urlpatterns += staticfiles_urlpatterns()
except:
    pass

multimedia/models.py
from django.db import models
from tinymce import models as tinymce_models


class Slideshow(models.Model):
    title = models.CharField(max_length=100)
    text = tinymce_models.HTMLField(blank=True)
    date = models.DateField()

    def __unicode__(self):
        return self.title


class Image(models.Model):
    title = models.CharField(max_length=100)
    text = tinymce_models.HTMLField(blank=True)
    author = models.CharField(max_length=200, blank=True)
    image = models.FileField(upload_to='dynamic/image/', blank=True)
    slideshow = models.ForeignKey(Slideshow)

    def __unicode__(self):
        return self.title

    def render_width(self):
        return self.get_image_width()


class Video(models.Model):
    title = models.CharField(max_length=100)
    text = tinymce_models.HTMLField(blank=True)
    video = models.URLField()
    author = models.CharField(max_length=200, blank=True)
    slideshow = models.ForeignKey(Slideshow)

    def __unicode__(self):
        return self.title


class Sound(models.Model):
    title = models.CharField(max_length=100)
    text = tinymce_models.HTMLField(blank=True)
    sound = models.URLField()
    author = models.CharField(max_length=200, blank=True)
    slideshow = models.ForeignKey(Slideshow)

    def __unicode__(self):
        return self.title

from south.modelsinspector import add_introspection_rules
add_introspection_rules([], ["^tinymce\.models\.HTMLField"])

multimedia/views.py
from django.shortcuts import render_to_response
from multimedia.models import *
from django.template import RequestContext


def slideshow_list(request):
    object_list = Slideshow.objects.all().order_by('-date')
    context = "media"
    return render_to_response('multimedia/slideshow_list.html',
        {'object_list': object_list, 'context': context},
        context_instance=RequestContext(request))


def detail(request, multimedia_id):
    slideshow = Slideshow.objects.get(id=multimedia_id)
    images = Image.objects.filter(slideshow=multimedia_id)
    videos = Video.objects.filter(slideshow=multimedia_id)
    sounds = Sound.objects.filter(slideshow=multimedia_id)
    context = "media"
    return render_to_response('multimedia/slideshow_detail.html',
        {'slideshow': slideshow, 'images': images, 'videos': videos, 'sounds': sounds, 'context': context},
        context_instance=RequestContext(request))

templates/multimedia/slideshow_detail.html
{% extends "base.html" %}

{% load multimedia_extras i18n %}

{% block main-content %}	
	<h2 >{{ slideshow.title }}</h2>

	{% autoescape off %}{{ slideshow.text }}{% endautoescape %}

	{% if images %}
	<div id="myCarousel" class="carousel slide">
    <!-- Carousel items -->
    <div class="carousel-inner">
		{% for item in images %}
		 <div class="item {% if forloop.first %}active{% endif %}">
		 	<a href="{{ item.image.url }}" title="{{ item.title }}" >
		 		<img src="{{ MEDIA_URL }}{{ item.image.url }}" /> 
		 	</a>
		 </div>
	    {% endfor %}
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
	{% endif %}
	
	{% if sounds %}
	<ul>
	{% for item in sounds %}
	<li>{{ item.title }}
	<embed src="{{MEDIA_URL}}swf/mediaplayer.swf" width="200" height="20" allowscriptaccess="always" allowfullscreen="true" flashvars="width=200&height=20&file={{ item.sound }}"/>
	 </li>
	{% endfor %}
	</ul>
	{% endif %}
	
	{% if videos %}
	<div class="images-box">
	{% for item in videos %}
	      <div style="float:left;margin:10px" class="well" >
	      <object width="180" height="135"><param name="movie" value="{{ item.video }}?width=180&theme=none&foreground=%23F7FFFD&highlight=%23FFC300&background=%23171D1B&additionalInfos=1&hideInfos=1&autoPlay=0&start=&colors=background%3A171D1B%3Bforeground%3AF7FFFD%3Bspecial%3AFFC300%3B"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><embed type="application/x-shockwave-flash" src="{{ item.video }}?width=180&theme=none&foreground=%23F7FFFD&highlight=%23FFC300&background=%23171D1B&additionalInfos=1&hideInfos=1&autoPlay=0&start=&colors=background%3A171D1B%3Bforeground%3AF7FFFD%3Bspecial%3AFFC300%3B" width="180" height="135" allowfullscreen="true" allowscriptaccess="always"></embed></object>
	      </div>
	{% endfor %}	
	</div> 
    {% endif %}
{% endblock %}

templates/multimedia/slideshow_list.html
{% extends "base.html" %}
{% load i18n multimedia_extras %}

{% block main-content %}
{% for slideshow in object_list %}

<a href="{{ slideshow.id }}">
	<div class="container">
		<div class="span1">
			{% if slideshow.image_set.all %}
			<img src="{% thumbnail slideshow.image_set.all.0.image 80 80 %}" class="small-sticker" />
			{% else %}
			<img src="{{ MEDIA_URL }}static/img/default_profile.jpg" width="80"  class="small-sticker"/>
			{% endif %}
		</div>
		<div class="span7">
			<b>{{ slideshow.title }}</b>
			{% if slideshow.text %}
			{% autoescape off %}
			{{ slideshow.text|truncatewords_html:13 }}
			{% endautoescape %}
			{% endif %}
		</div>
	</div>
</a>
<hr />

{% endfor %}
{% endblock %}