music/urls.py
from django.conf.urls.defaults import *
from music import views

urlpatterns = patterns('',
    url(r'^song/(?P<song_id>\d+)/$', views.song_detail, name="music-detail"),
    url(r'^album/$', views.album_list, name="album-list"),
    url(r'^album/(?P<album_id>\d+)/$', views.album_detail, name="album-detail"),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps import Sitemap, FlatPageSitemap, GenericSitemap
from django.contrib import admin

from blog.models import *
from blog.views import artists, artist_posts, LatestPost
from music.models import *
from gig.views import GigsFeed

from settings import MEDIA_ROOT

admin.autodiscover()


class BaseSitemap(Sitemap):
    priority = 0.8

    def items(self):
        return ['/', '/blog/', '/gig/', '/link/', '/album/']

    def location(self, obj):
        return obj

feeds = {
    'latest': LatestPost,
    'concerts': GigsFeed,
}

blog_sitemap_dict = {
    'queryset': Post.objects.all(),
    'date_field': 'date',
}

sitemaps = {
    'flatpages': FlatPageSitemap,
    'blog': GenericSitemap(blog_sitemap_dict),
    'list': BaseSitemap(),
    'album': AlbumSitemap(),
    'song': SongSitemap(),
}

urlpatterns = patterns('',
    url(r'^contact/', include('contact_form.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^map/', artists, name="map"),
    url(r'^ref/(?P<object_id>\d+)/$', artist_posts, name="artist-posts"),
    url(r'^gig/', include('gig.urls')),
    url(r'^link/$', include('link.urls')),
    url(r'^music/', include('music.urls')),
    url(r'^multimedia/', include('multimedia.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^feeds/latest/$', LatestPost()),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps})
)

urlpatterns += patterns('django.views.generic.simple',
    ('^$', 'redirect_to', {'url': 'blog/'}),
)

try:
    import settings_local
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, 'show_indexes': True}),
    )
    urlpatterns += staticfiles_urlpatterns()
except:
    pass

music/models.py
from django.db import models
from django.contrib.sitemaps import Sitemap
from tinymce import models as tinymce_models


class AlbumCategory(models.Model):
    name = models.CharField(max_length=100)
    order = models.IntegerField()

    def __unicode__(self):
        return self.name


class Album(models.Model):
    title = models.CharField(max_length=100)
    text = tinymce_models.HTMLField(blank=True)
    cover = models.FileField(upload_to='media/static/album/cover/', blank=True)
    date = models.DateField()
    album_category = models.ForeignKey(AlbumCategory)
    publish = models.BooleanField()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/music/album/%i/" % self.id


class AlbumArchive(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=100)
    text = tinymce_models.HTMLField(blank=True)
    archive = models.URLField(verify_exists=False)


class Song(models.Model):
    title = models.CharField(max_length=100)
    soundfile = models.URLField(verify_exists=False, blank=True, null=True)
    album = models.ForeignKey(Album, blank=True)
    track_number = models.IntegerField()
    text = tinymce_models.HTMLField(blank=True)
    lyrics = tinymce_models.HTMLField(blank=True)
    tab = models.FileField(upload_to='media/static/tab/', blank=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/music/song/%i/" % self.id


class Track(models.Model):
    song = models.ForeignKey(Song)
    order = models.PositiveIntegerField()
    instrument = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    url = models.URLField(verify_exists=True)


class AlbumSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5

    def items(self):
        return Album.objects.all()

    def lastmod(self, obj):
        return obj.date


class SongSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5

    def items(self):
        return Song.objects.all()

    def lastmod(self, obj):
        return obj.album.date

from south.modelsinspector import add_introspection_rules
add_introspection_rules([], ["^tinymce\.models\.HTMLField"])

music/views.py
from django.shortcuts import render_to_response
from music.models import *
from django.template import RequestContext


def album_list(request):
    albums = Album.objects.filter(publish=1).select_related().order_by('album_category__order', '-date')
    context = "music"
    return render_to_response('music/album_list.html',
        {'albums': albums, 'context': context},
        context_instance=RequestContext(request))


def album_detail(request, album_id):
    album = Album.objects.get(id=album_id)
    songs = Song.objects.filter(album=album_id).order_by('track_number')
    context = "music"
    return render_to_response('music/album_detail.html',
        {'album': album, 'songs': songs, 'context': context},
        context_instance=RequestContext(request))


def playlist(request):
    songs = Song.objects.select_related().order_by('-album__date', 'track_number')
    return render_to_response('music/playlist.html', {'songs': songs},
        context_instance=RequestContext(request),
        mimetype='application/xspf+xml')


def song_detail(request, song_id):
    song = Song.objects.get(id=song_id)
    context = "music"
    return render_to_response('music/song_detail.html',
        {'song': song, 'context': context},
        context_instance=RequestContext(request))

templates/music/album_detail.html
{% extends "base.html" %}
{% load i18n multimedia_extras %}


{% block main-content %}	


<h2><i>{{ album.title }}</i></h2>
<p><span class="badge badge-inverse">{{ album.date|date:"F Y" }}</span></p>


<div class="container">
	<div class="span3">
		{% if album.cover %}
		<div class="well"><img class="sticker" src="{% thumbnail album.cover 300 300 %}"  /></div>
		{% else %}
		<img src="{{ MEDIA_URL }}static/img/default_profile.jpg" width="300" />
		{% endif %}	    
	</div>
	<div class="span5">
		<table class="table" >
			{% for song in songs %}
			<tr>
				<td >{{ song.track_number }}. </td>
				<td>{{ song.title }}</td>
				<td>{% if song.soundfile %}<a href="{{ song.soundfile }}" title="{{ song.title }}" ><i class="icon-download"></i> {% trans 'Télécharger' %}</a>{% endif %}</td>
				<td>{% if song.lyrics %}<a class="soft" href="{% url music-detail song.id %}" class="text" title="Texte">Texte</a>{% endif %}</td>
				<td>{% if song.tab %}<a class="soft" href="{{ song.tab.url }}" class="tab" title="Partition">♪ Tab.</a>{% endif %}</td>
				{% comment %}<td>{% if song.track_set.all %}<a class="soft" href="{% url song-remix song.id %}" class="tab" title="Remix">remix</a>{% endif %}</td>{% endcomment %}
			</tr>
			{% endfor %}
			
		</table>
		<div class="alert alert-info">	
			Cette musique, comme l'ensemble des contenus de ce site, est sous licence libre. Elle est donc en téléchargement légal et gratuit pour toute utilisation non commerciale.
		</div>
	</div>
</div>


{% if album.albumarchive_set.all %}
<h3>Téléchargements de l'album disponibles</h3> 
<p>
	{% for archive in album.albumarchive_set.all %}
	<a class="badge" href="{{ archive.archive }}">{{ archive.title }}</a>
	{% endfor %}
	
</p>
{% endif %}


{% autoescape off %}
{{ album.text }}
{% endautoescape %}


{% endblock %}

templates/music/album_list.html
{% extends "base.html" %}
{% load i18n %}
{% load multimedia_extras %}

{% block main-content %}
{% regroup albums by album_category as category_list %}

{% for album_category in category_list %}

<h2>{{ album_category.grouper }}</h2>
<ul class='thumbnails'>
	{% for album in album_category.list %}
	<li class="span3">
		<a class="thumbnail" href="{% url album-detail album.id %}">
			<img src="{% thumbnail album.cover 250 250 %}" class="small-sticker"/>
			<div class="caption">
				<h6>{{ album.title }}</h6>
				<p><span class="badge badge-inverse">{{album.date|date:"Y" }}</span> {{ album.song_set.all|length }} {% trans 'titres' %}</p>
			</div>
		</a> 
		{% endfor %}
	</li>
</ul>

{% endfor %}

{% endblock %}

templates/music/song_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block main-content %}

<h2>{{ song.title }}</h2>
<p class='subtitle'>(sur l'album <i><a href="{% url album-detail song.album.id %}">{{ song.album.title }}</a></i>)</p>

{% if song.lyrics %}
{% autoescape off %}
{{ song.lyrics }}
{% endautoescape %}
{% endif %}

{% if song.text %}
<h3>Compléments</h3>
{% autoescape off %}
{{ song.text }}
{% endautoescape %}
{% endif %}

{% endblock %}

templates/music/song_list.html
{% extends "base.html" %}
{% block main_content %}
{% regroup object_list|dictsort:"track_number" by album as album_list %}<h3>albums</h3>{% for album in album_list %}   <div class="bloc">
    <h3>{{ album.grouper }}</h3>  
    {% autoescape off %}{{ album.grouper.text }}{% endautoescape %}
    <img src="{{ album.grouper.get_cover_url }}" width="150" style="float:left;"/>    <table>        {% for item in album.list %}        <tr>
        <td>{{ item.track_number }} <a href="{{ item.id }}">{{ item.title }}</a></td>
        <td>
        <embed 		src="{{MEDIA_URL}}swf/mediaplayer.swf" 		width="200" 		height="20"		allowscriptaccess="always" 		allowfullscreen="true" 		flashvars="width=200&height=20&file={{ item.soundfile }}" 		/></td>
        </tr>        {% endfor %}    </table>
   </div>{% endfor %}

{% endblock %}