blog/urls.py
from django.conf.urls.defaults import *
from django.views.generic.list_detail import object_detail

from blog.models import Post
from blog import views

info_dict = {
    'queryset': Post.objects.all().order_by('-date'),
    'paginate_by': 5,
}

info_dict_detail = {
    'queryset': Post.objects.all().order_by('-date'),
    'extra_context': {'context': 'blog'}
}

urlpatterns = patterns('',
    url(r'^$', views.post_list, name="blog-list"),
    url(r'^(?P<object_id>\d+)/$', object_detail, info_dict_detail, name="blog-detail"),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps import Sitemap, FlatPageSitemap, GenericSitemap
from django.contrib import admin

from blog.models import *
from blog.views import artists, artist_posts, LatestPost
from music.models import *
from gig.views import GigsFeed

from settings import MEDIA_ROOT

admin.autodiscover()


class BaseSitemap(Sitemap):
    priority = 0.8

    def items(self):
        return ['/', '/blog/', '/gig/', '/link/', '/album/']

    def location(self, obj):
        return obj

feeds = {
    'latest': LatestPost,
    'concerts': GigsFeed,
}

blog_sitemap_dict = {
    'queryset': Post.objects.all(),
    'date_field': 'date',
}

sitemaps = {
    'flatpages': FlatPageSitemap,
    'blog': GenericSitemap(blog_sitemap_dict),
    'list': BaseSitemap(),
    'album': AlbumSitemap(),
    'song': SongSitemap(),
}

urlpatterns = patterns('',
    url(r'^contact/', include('contact_form.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^map/', artists, name="map"),
    url(r'^ref/(?P<object_id>\d+)/$', artist_posts, name="artist-posts"),
    url(r'^gig/', include('gig.urls')),
    url(r'^link/$', include('link.urls')),
    url(r'^music/', include('music.urls')),
    url(r'^multimedia/', include('multimedia.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^feeds/latest/$', LatestPost()),
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps})
)

urlpatterns += patterns('django.views.generic.simple',
    ('^$', 'redirect_to', {'url': 'blog/'}),
)

try:
    import settings_local
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT, 'show_indexes': True}),
    )
    urlpatterns += staticfiles_urlpatterns()
except:
    pass

blog/models.py
from django.db import models
from tinymce import models as tinymce_models


class Category(models.Model):
    title = models.CharField(max_length=100)

    def __unicode__(self):
        return self.title


class Post(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category)
    image = models.FileField(upload_to='dynamic/blog_image', blank=True)
    date = models.DateField()
    text = tinymce_models.HTMLField()

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/blog/%i/" % self.id


class Artist(models.Model):
    name = models.CharField(max_length=100, unique=True)
    posts = models.ManyToManyField(Post)
    image = models.ImageField(upload_to='dynamic/artist_image',
                              blank=True, null=True)
    birth = models.DateField(blank=True, null=True)
    death = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return self.name

from south.modelsinspector import add_introspection_rules
add_introspection_rules([], ["^tinymce\.models\.HTMLField"])

blog/views.py
from datetime import datetime

from django.contrib.syndication.views import Feed
from django.core.paginator import InvalidPage
from django.views.generic.list_detail import object_list
from django.shortcuts import render_to_response
from django.template import RequestContext

from blog.models import Post, Artist
from music.models import *
from link.models import *

from name_paginator import NamePaginator


class LatestPost(Feed):
    title = "sam - rss news"
    link = "/blog/"
    description = "Le flux rss des news du site de sam"

    def items(self):
        return Post.objects.order_by('-date')[:5]
    item_author_link = 'http://www.sam-lesite.fr/'
    item_author_name = 'sam'

    def item_pubdate(self, item):
        return datetime(item.date.year, item.date.month, item.date.day)


def post_list(request):
    q = Post.objects.all().order_by('-date')
    page = int(request.GET.get('page', '1'))
    context = "blog"
    return object_list(request, queryset=q, paginate_by=5,
                       extra_context={'page': page, 'context': context})


def artists(request):
    artists = Artist.objects.all().order_by('name')
    paginator = NamePaginator(artists, on="name", per_page=25)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1
    try:
        page = paginator.page(page)
    except (InvalidPage):
        page = paginator.page(paginator.num_pages)
    context = "artist"
    return render_to_response('blog/artists.html',
                              {"page": page, "context": context},
                              context_instance=RequestContext(request))


def artist_posts(request, object_id):
    artists = Artist.objects.all().order_by('name')
    artist = Artist.objects.get(id=object_id)
    context = "artist"
    return render_to_response('blog/artist.html',
                              {'artist': artist, 'artists': artists,
                              "context": context},
                              context_instance=RequestContext(request))

templates/blog/artist.html
{% extends "base.html" %}
{% load comments multimedia_extras i18n %}

{% block main-content %}
<div class="container">
	<div class="span1">
		&nbsp
	</div>
	<div class="span7">
		<ul class="thumbnails">
			<li>
				<div class="thumbnail" style="text-align:center">
					{% if artist.image %}<img alt="{{ artist.name }}" title="{{ artist.name }}" class="sticker" src="{% thumbnail artist.image 80 80 %}" />{% else %}<img src="{{ MEDIA_URL }}static/img/default_profile.jpg" width="80" alt="{{ artist.name }}" title="{{ artist.name }}" class="sticker"  />{% endif %}
					<div class="caption"><h6>{{ artist.name }}</h6>
					</div>
				</div>

			</li>
		</ul>
	</div>
</div>
{% for post in artist.posts.all|dictsortreversed:"date" %}
{% include 'blog/post.html' %}
{% endfor %}
</div>
{% endblock %}

templates/blog/artists.html
{% extends 'base.html' %}
{% load multimedia_extras %}

{% block main-content %}

<div class="pagination">
	{% for p in page.paginator.pages %}
	{% ifequal p page %}
	<li class="active"><a>{{ page }}</a></li>
	{% else %}
	<li><a href="?page={{ p.number }}">{{ p }}</a></li>
	{% endifequal %} 
	{% endfor %}
</div>

<ul class="thumbnails">
	{% for artist in page.object_list %}
	<li class="span1">
		<a class="thumbnail" href="{% url artist-posts artist.id %}"> {% if artist.image %}<img alt="{{ artist.name }}" title="{{ artist.name }}" class="small-sticker" src="{% thumbnail artist.image 80 80 %}" />{% else %}<img src="{{ MEDIA_URL }}static/img/default_profile.jpg" width="80" alt="{{ artist.name }}" title="{{ artist.name }}" class="small-sticker"  />{% endif %}
		</a>
	</li>
	{% endfor %}
</ul>

{% endblock %}

templates/blog/post.html
{% load comments %}
{% load i18n multimedia_extras %}

<div class="container">
  <div class="span1">
    <h2>&nbsp;</h2>
    <span class="badge badge-inverse">{{ post.date|date:"d b Y" }}</span>
</div>
<div class="span7">
    <h2><a href="{% url blog-detail post.id %}">{{ post.title }}</a></h2>
    <p><span class="label">{{ post.category }}</span></p>
    {% if post.image %}
    <img src="{% thumbnail post.image 200 160 %}" style="float:left;margin-right:10px;margin-bottom:10px;"/>
    {% endif %}
    {% if truncate == "True" %}
    {% autoescape off %}
    {{ post.text|truncatewords_html:100 }}
    {% endautoescape %}
    <p class="read_more"><a href="{% url blog-detail post.id %}">lire la suite</a></p>
    {% else %}
    {% autoescape off %}
    {{ post.text }}
    {% endautoescape %}
    {% endif %}
</div>
</div>
<hr />

templates/blog/post_detail.html
{% extends "base.html" %}

{% load multimedia_extras %}

{% block main-content %}	

{% include "blog/post.html" with post=object %}

{% if object.artist_set.all %}
<div class="container">
	<div class="span1">&nbsp;</div>
	<div class="span7">
		<ul class="thumbnails">
			{% for artist in object.artist_set.all %}
			<li class="span1">
				<a class="thumbnail" href="{% url artist-posts artist.id %}"> 
					{% if artist.image %}
					<img alt="{{ artist.name }}" title="{{ artist.name }}" class="small-sticker" src="{% thumbnail artist.image 80 80 %}" />
					{% else %}
					<img src="{{ MEDIA_URL }}static/img/default_profile.jpg" width="80" alt="{{ artist.name }}" title="{{ artist.name }}" class="small-sticker"  />{% endif %}
				</a>
			</li>
			{% endfor %}
		</ul>
	</div>
</div>
{% endif %}

{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}

{% load i18n multimedia_extras %}

{% block rss %}
<link rel="alternate" type="application/rss+xml" href="http://sam-lesite.alwaysdata.net/feeds/latest/" title="sam - flux rss" />
{% endblock %}


{% block main-content %}

{% for post in object_list %}
{% include "blog/post.html" with truncate="True" %}
{% endfor %}

<div class="pagination">
	<ul>
		{% for page_number in page_range %}
		{% ifequal page page_number %}
		<li class="active">
			<a >{{ page_number }}</a>
		</li>
		{% else %}
		<li>
			<a href="./?page={{page_number}}" >{{ page_number }}</a>
		</li>
		{% endifequal %}
		{% endfor %}
	</ul>
</div>
{% endblock %}